### PR TITLE
change page min-height to 85vh to position the footer always bottom

### PR DESCRIPTION
**Pull request by onuriltan**

### CODE REVIEW

**Comment by onuriltan** [comment]
Hello :) I've just started a chat project with vue and node and yours looks pretty awesome :) I thought I can contribute your project somehow

After: 
image

Before:
image

**Comment by luvuong-le** [comment]
@onuriltan Hey Onur! I appreciate the contribution :) I know the styling I have isn't 100% perfect so thank you! 

I'd love to see your chat project once you finish it :)

**Comment by onuriltan** [comment]
Hey @luvuong-le . Thanks for the response :) I will let you know when I finish my project

**Comment by luvuong-le** [comment]
@onuriltan Great! :)

**Pull request merged**
